name: Release action
on:
  push:
    tags:
      - 'v*.*'
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: 'Checkout source'
        with:
          fetch-depth: 1
      - run: |
            git fetch --prune --unshallow --tags
            git tag --list

      - name: 'Setup node'
        uses: actions/setup-node@v1
        with:
          node-version: '16.10.0'

      - name: 'Install'
        run: npm i
        
      - name: 'Run'
        run: npm run release